/**
 * @file gdt.h
 * @brief function definitions for the gdt
 */

#include "gdt.h"
#include "bits.h"
#include "print.h"

/// gdt is stored globally so it can easily be modified later
GDT gdt = {
    .null = {0, 0, 0, 0, 0, 0},
    .code = {0, 0, 0, 0x9A, 0xA0, 0},
    .data = {0, 0, 0, 0x92, 0xA0, 0}
};

/// gdt descriptor also stored globaly so the gdt size can be updated
GDTDescriptor gdtDescriptor = {
    (u16)(sizeof(gdt) * 8 - 1),
    (u64)&gdt
};

/// wrapper because the gdt is obfuscated to this file
void init_gdt() {
    load_gdt(&gdtDescriptor);
}

/**
 * @brief asm function for loading gdt
 * @param gdtDescriptor pointer to the gdtDescriptor
 * @details NAKED attribute removes the stack frame generated by gcc
 *          so the whole function is shown by the asm block.
 */
NAKED void load_gdt(GDTDescriptor* gdtDescriptor) {
    asm volatile (
        "lgdt %0\n"
        "mov ax, 0x10\n"
        "mov ds, ax\n"
        "mov es, ax\n"
        "mov fs, ax\n"
        "mov gs, ax\n"
        "mov ss, ax\n"
        "pop rdi\n"
        "mov rax, 0x08\n"
        "push rax\n"
        "push rdi\n"
        "retfq"
        :
        : "m" (*gdtDescriptor)
        : "rdi", "rax", "memory"
    );
}

/// clears 64 bit in code segment of gdt then reloads it
void enter_compatability_mode(void) {
    CLEAR_BIT(gdt.code.limit1Flags, 3);
    load_gdt(&gdtDescriptor);
}

/// sets 64 bit in code segment of gdt then reloads it
void exit_compatability_mode(void) {
    SET_BIT(gdt.code.limit1Flags, 3);
    load_gdt(&gdtDescriptor);
}
